---
- name: Download binary
  become: yes
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: $HOME/node_exporter{{ node_exporter_version }}.tar.gz

- name: Unarchive a file that is already on the remote machine
  become: yes
  unarchive:
    src: $HOME/node_exporter{{ node_exporter_version }}.tar.gz
    dest: /usr/sbin
    remote_src: yes
    mode: +x
    extra_opts:
      - --strip-components=1
      -  node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter

- name: Create group for user
  become: True
  group:
    state: present
    name: node_exporter

- name: Create user
  become: yes
  user:
    create_home: no
    state: present
    name: node_exporter
    group: node_exporter
    shell: /sbin/nologin

- name: Create systemd service
  become: yes
  template:
    src: "templates/etc/systemd/system/node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
  notify: restart node_exporter.service
